In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Barca_accidents_opendata.csv")
df.head()

C:\Users\ESHAN\AppData\Local\Temp\ipykernel_20600\83649003.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Barca_accidents_opendata.csv")

,case_id,district_id,district_name,neighborhood_id,neighborhood_name,street_code,street_name,postal_code,weekday_name,weekday,...,cause_incident,n_deaths,n_wounded_mild,n_wounded_severe,n_victims,n_vehicles,utm_coordinate_y,utm_coordinate_x,longitude,latitude
0,2015S005807,-1.0,Desconegut,-1.0,Desconegut,-1.0,Desconegut,Desconegut,Dimarts,Dm,...,No és causa del vianant,0.0,2.0,0.0,2.0,2.0,-1,-1,NaN,NaN
1,2015S007685,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,134801.0,Freser,0208 0208,Dimarts,Dm,...,Desobeir el senyal del semàfor,0.0,1.0,0.0,1.0,1.0,"4585420,58","431779,16",NaN,NaN
2,2015S001364,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,161407.0,Indústria,0336 0336,Dissabte,Ds,...,No és causa del vianant,0.0,1.0,0.0,1.0,1.0,"4585555,86","431913,65",NaN,NaN
3,2015S004325,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,226400.0,Las Navas de Tolosa,0343 0343,Divendres,Dv,...,No és causa del vianant,0.0,1.0,0.0,1.0,2.0,"4585565,44","431946,45",NaN,NaN
4,2015S005540,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,95506.0,Conca,0032 0034,Divendres,Dv,...,No és causa del vianant,0.0,2.0,0.0,2.0,1.0,"4585260,16","431530,84",NaN,NaN

In [11]:
df.longitude.isnull().sum()

56310

In [9]:
df.shape

(110655, 27)

In [214]:
df.isnull().sum()

case_id                  0
district_id              1
district_name            1
neighborhood_id          1
neighborhood_name        1
street_code              1
street_name              2
postal_code           4006
weekday_name             0
weekday               7660
type_day              7660
year                     1
month                    1
month_name               1
day                      1
hour                     1
cyrcadian                0
cause_incident           1
n_deaths                 1
n_wounded_mild           1
n_wounded_severe         1
n_victims                1
n_vehicles               1
utm_coordinate_y         1
utm_coordinate_x         1
longitude            54701
latitude             54701
dtype: int64

In [221]:
df[df['district_id'].isnull()]

Empty DataFrame
Columns: [case_id, district_id, district_name, neighborhood_id, neighborhood_name, street_code, street_name, postal_code, weekday_name, weekday, type_day, year, month, month_name, day, hour, cyrcadian, cause_incident, n_deaths, n_wounded_mild, n_wounded_severe, n_victims, n_vehicles, utm_coordinate_y, utm_coordinate_x, longitude, latitude]
Index: []

[0 rows x 27 columns]

In [220]:
df = df.drop(10008, axis = 'rows')

In [222]:
df1 = df.drop(["postal_code", "latitude", "longitude", ], axis = 'columns')

UTM system(WGS84): Easting is utm_coordinate_x
Northing is utm_coordinate_y
zone is 31

In [223]:
#convert language

In [224]:
def uniquePortList(df, col):
    listt = []
    listt = df.loc[:,col].unique()
    return(listt.tolist())

In [225]:
from googletrans import Translator, constants
from pprint import pprint
# init the Google API translator
translator = Translator()

In [226]:
# translate a spanish text to english text (by default)
def convertLang(portList): 
    convList =[]
    translations = translator.translate(portList)
    for translation in translations:
        convList.append(translation.text)
    return convList

In [227]:
def conversion(df):
    col_name = ["weekday_name", "weekday", "type_day", "year", "month", "month_name", "day", "hour"
, "cyrcadian", "cause_incident", "type_day"]
    for n in range(len(col_name)):
        
        portList = []
        uniqueEngList = []
        
        curr_col = col_name[n]
        print(curr_col)
        portList = uniquePortList(df, curr_col)
        
        #convert
        uniqueEngList = convertLang(portList)
        
        for i in range(len(portList)):

            df.loc[df1[curr_col] == portList[i], curr_col] = uniqueEngList[i]
df2 = df1
conversion(df2)

weekday_name
weekday
type_day
year
month
month_name
day
hour
cyrcadian
cause_incident
type_day

In [228]:
df3= df2.copy()
df3.head()

,case_id,district_id,district_name,neighborhood_id,neighborhood_name,street_code,street_name,weekday_name,weekday,type_day,...,hour,cyrcadian,cause_incident,n_deaths,n_wounded_mild,n_wounded_severe,n_victims,n_vehicles,utm_coordinate_y,utm_coordinate_x
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,2015S001364,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,161407.0,Indústria,Saturday,Ds,Labor,...,21.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,1.0,"4585555,86","431913,65"
3,2015S004325,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,226400.0,Las Navas de Tolosa,Friday,Dv,Labor,...,9.0,morning,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4585565,44","431946,45"
4,2015S005540,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,95506.0,Conca,Friday,Dv,Labor,...,20.0,Afternoon,It is not the cause of the pedestrian,0.0,2.0,0.0,2.0,1.0,"4585260,16","431530,84"

In [229]:
df3.cause_incident.unique()

array(['1', 'It is not the cause of the pedestrian',
       'Disobey the traffic light signal', 'others',
       'Walk along the road', 'Cross over the pedestrian crossing',
       'Disobey other signals', 'unknown'], dtype=object)

In [230]:
df3.weekday.unique()

array(['1', 'Ds', 'Dv', 'Dl', 'Dc', 'Dj', 'Dg', nan, '5', '4', '2', '3',
       '7', '6'], dtype=object)

In [231]:
df3.type_day.unique()

array(['1', 'Labor', nan], dtype=object)

In [232]:
df3.weekday_name.unique()

array(['1', 'Saturday', 'Friday', 'Monday', 'Wednesday', 'Thursday',
       'sunday', 'Tuesday'], dtype=object)

In [233]:
df3 = df3.drop(df3[df3.weekday_name == '1'].index)

In [234]:
df3.weekday_name.unique()

array(['Saturday', 'Friday', 'Monday', 'Wednesday', 'Thursday', 'sunday',
       'Tuesday'], dtype=object)

In [238]:
df3[df3.weekday == 'Dm']

Empty DataFrame
Columns: [case_id, district_id, district_name, neighborhood_id, neighborhood_name, street_code, street_name, weekday_name, weekday, type_day, year, month, month_name, day, hour, cyrcadian, cause_incident, n_deaths, n_wounded_mild, n_wounded_severe, n_victims, n_vehicles, utm_coordinate_y, utm_coordinate_x]
Index: []

[0 rows x 24 columns]

In [239]:
df3[df3.weekday_name == 'Tuesday']

,case_id,district_id,district_name,neighborhood_id,neighborhood_name,street_code,street_name,weekday_name,weekday,type_day,...,hour,cyrcadian,cause_incident,n_deaths,n_wounded_mild,n_wounded_severe,n_victims,n_vehicles,utm_coordinate_y,utm_coordinate_x
10014,2021S003063,10.0,Sant Martí,64,el Camp de l'Arpa del Clot,194406.0,Maragall,Tuesday,NaN,NaN,...,10.0,morning,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,3.0,431648.6,4585174.8
10030,2021S004906,10.0,Sant Martí,72,Sant Martí de Provençals,158504.0,Huelva,Tuesday,NaN,NaN,...,2.0,Nit,It is not the cause of the pedestrian,0.0,0.0,0.0,0.0,2.0,432655.93,4585333.46
10042,2021S000673,10.0,Sant Martí,70,el Besòs i el Maresme,701281.0,Llevant,Tuesday,NaN,NaN,...,20.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,434848.19,4584967.78
10063,2021S001749,10.0,Sant Martí,68,el Poblenou,701265.0,Litoral (Besòs),Tuesday,NaN,NaN,...,17.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,4.0,433557.81,4582963.81
10066,2021S002746,10.0,Sant Martí,68,el Poblenou,332000.0,Taulat,Tuesday,NaN,NaN,...,15.0,Afternoon,Walk along the road,0.0,1.0,0.0,1.0,1.0,433682.87,4583588.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90662,2013S003640,9.0,Sant Andreu,91-9-62,el Congrés i els Indians,191907.0,Manigua,Tuesday,2,Labor,...,14.0,Afternoon,unknown,0.0,1.0,0.0,1.0,2.0,"4586095,90","431446,97"
90663,2013S005558,9.0,Sant Andreu,91-9-63,Navas,86108.0,Concepción Arenal,Tuesday,2,Labor,...,14.0,Afternoon,unknown,0.0,1.0,0.0,1.0,2.0,"4585889,51","431816,04"
90672,2013S001101,9.0,Sant Andreu,93-9-57,la Trinitat Vella,34400.0,Bàrcino,Tuesday,2,Labor,...,23.0,Nit,unknown,0.0,1.0,0.0,1.0,1.0,"4589282,42","432711,12"
90678,2013S008898,9.0,Sant Andreu,93-9-57,la Trinitat Vella,209900.0,Meridiana,Tuesday,2,Labor,...,14.0,Afternoon,unknown,0.0,1.0,0.0,1.0,2.0,"4588897,08","432220,64"
90684,2013S004621,9.0,Sant Andreu,92-9-60,Sant Andreu,209900.0,Meridiana,Tuesday,2,Labor,...,17.0,Afternoon,unknown,0.0,0.0,0.0,0.0,2.0,"4587063,39","431781,83"

In [240]:
df3.isnull().sum()

case_id                 0
district_id             0
district_name           0
neighborhood_id         0
neighborhood_name       0
street_code             0
street_name             1
weekday_name            0
weekday              7659
type_day             7659
year                    0
month                   0
month_name              0
day                     0
hour                    0
cyrcadian               0
cause_incident          0
n_deaths                0
n_wounded_mild          0
n_wounded_severe        0
n_victims               0
n_vehicles              0
utm_coordinate_y        0
utm_coordinate_x        0
dtype: int64

Monday is 1 and Dl
Tuesday is Dm
Wed is Dc
Thur is Dj
Dri is Dv
Sat is Ds

In [241]:
def replaceWeekday(df):
    keys = ['Dm', 'Ds', 'Dv', 'Dl', 'Dc', 'Dj', 'Dg']
    days = [2, 6, 5, 1, 3, 4, 7]
    day_name = ['Tuesday', 'Saturday', 'Friday', 'Monday', 'Wednesday', 'Thursday', 'sunday']
    for el in range(len(keys)):
        df.loc[df['weekday'] == keys[el], 'weekday'] = days[el] 
        df.loc[df['weekday_name'] == day_name[el], 'weekday'] = days[el]
        #print(keys[el])
    return df

In [242]:
df4 = replaceWeekday(df3)
df4.head()

,case_id,district_id,district_name,neighborhood_id,neighborhood_name,street_code,street_name,weekday_name,weekday,type_day,...,hour,cyrcadian,cause_incident,n_deaths,n_wounded_mild,n_wounded_severe,n_victims,n_vehicles,utm_coordinate_y,utm_coordinate_x
2,2015S001364,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,161407.0,Indústria,Saturday,6,Labor,...,21.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,1.0,"4585555,86","431913,65"
3,2015S004325,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,226400.0,Las Navas de Tolosa,Friday,5,Labor,...,9.0,morning,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4585565,44","431946,45"
4,2015S005540,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,95506.0,Conca,Friday,5,Labor,...,20.0,Afternoon,It is not the cause of the pedestrian,0.0,2.0,0.0,2.0,1.0,"4585260,16","431530,84"
6,2015S002980,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,194406.0,Maragall,Monday,1,Labor,...,18.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,1.0,"4585336,24","431615,03"
7,2015S006560,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,161407.0,Indústria,Monday,1,Labor,...,20.0,Afternoon,It is not the cause of the pedestrian,0.0,2.0,0.0,2.0,2.0,"4585306,47","431650,48"

In [243]:
(df4['weekday'] == 'Ds')

2         False
3         False
4         False
6         False
7         False
          ...
110633    False
110634    False
110635    False
110637    False
110654    False
Name: weekday, Length: 102603, dtype: bool

In [244]:
df4[df4.weekday_name == 'sunday']

,case_id,district_id,district_name,neighborhood_id,neighborhood_name,street_code,street_name,weekday_name,weekday,type_day,...,hour,cyrcadian,cause_incident,n_deaths,n_wounded_mild,n_wounded_severe,n_victims,n_vehicles,utm_coordinate_y,utm_coordinate_x
17,2015S008823,10.0,Sant Martí,65.0,el Clot,115603.0,Espronceda,sunday,7,Labor,...,10.0,morning,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4585118,68","432760,33"
46,2015S008825,10.0,Sant Martí,73.0,la Verneda i la Pau,153205.0,Guipúscoa,sunday,7,Labor,...,17.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4586017,93","433561,94"
72,2015S005371,10.0,Sant Martí,71.0,Provençals del Poblenou,701414.0,C-31,sunday,7,Labor,...,1.0,Nit,others,0.0,2.0,0.0,2.0,2.0,"4585808,01","433936,57"
78,2015S000979,10.0,Sant Martí,69.0,Diagonal Mar i el Front Marítim del Poblenou,322608.0,Selva de Mar,sunday,7,Labor,...,19.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4584169,95","434429,56"
81,2015S003168,10.0,Sant Martí,69.0,Diagonal Mar i el Front Marítim del Poblenou,701265.0,Litoral (Besòs),sunday,7,Labor,...,22.0,Nit,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4584391,21","434814,70"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110616,2019S010012,10.0,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,701266.0,Litoral (Llobregat) ...,sunday,7,Labor,...,16.0,Afternoon,It is not the cause of the pedestrian,0.0,2.0,0.0,2.0,2.0,"4584049,58","434443,92"
110617,2019S010013,10.0,Sant Martí,71,Provençals del Poblenou,701414.0,Selva de Mar / Corts Catalanes ...,sunday,7,Labor,...,18.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4585249,15","433366,47"
110618,2019S010014,8.0,Nou Barris,44,Vilapicina i la Torre Llobeta,45701.0,Quinze ...,sunday,7,Labor,...,21.0,Afternoon,others,0.0,1.0,0.0,1.0,2.0,"4586808,85","431134,74"
110619,2019S010015,9.0,Sant Andreu,61,la Sagrera,201308.0,Martí Molins ...,sunday,7,Labor,...,23.0,Nit,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,1.0,"4586353,38","432278,77"
110620,2019S010016,2.0,Eixample,8,l'Antiga Esquerra de l'Eixample,223606.0,Muntaner / Mallorca ...,sunday,7,Labor,...,21.0,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4582504,97","429522,49"

In [245]:
df4.isnull().sum()

case_id                 0
district_id             0
district_name           0
neighborhood_id         0
neighborhood_name       0
street_code             0
street_name             1
weekday_name            0
weekday                 0
type_day             7659
year                    0
month                   0
month_name              0
day                     0
hour                    0
cyrcadian               0
cause_incident          0
n_deaths                0
n_wounded_mild          0
n_wounded_severe        0
n_victims               0
n_vehicles              0
utm_coordinate_y        0
utm_coordinate_x        0
dtype: int64

#we have all weekday_name, we can use it to find weekdays(int) and type_day (sat and sunday are off)

In [246]:
df4.type_day.unique()

array(['Labor', nan], dtype=object)

#type_day has labour on sunday as well, which means its incorrect data.

In [247]:
def type_day_correction(df):
    df['working'] = df['weekday_name'].apply(lambda x: 0 if 'sunday' or 'Saturday' else 1)
    return df

LAter take into account other holidays

In [248]:
df5 = type_day_correction(df4)

In [249]:
df5.head()

,case_id,district_id,district_name,neighborhood_id,neighborhood_name,street_code,street_name,weekday_name,weekday,type_day,...,cyrcadian,cause_incident,n_deaths,n_wounded_mild,n_wounded_severe,n_victims,n_vehicles,utm_coordinate_y,utm_coordinate_x,working
2,2015S001364,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,161407.0,Indústria,Saturday,6,Labor,...,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,1.0,"4585555,86","431913,65",0
3,2015S004325,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,226400.0,Las Navas de Tolosa,Friday,5,Labor,...,morning,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,2.0,"4585565,44","431946,45",0
4,2015S005540,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,95506.0,Conca,Friday,5,Labor,...,Afternoon,It is not the cause of the pedestrian,0.0,2.0,0.0,2.0,1.0,"4585260,16","431530,84",0
6,2015S002980,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,194406.0,Maragall,Monday,1,Labor,...,Afternoon,It is not the cause of the pedestrian,0.0,1.0,0.0,1.0,1.0,"4585336,24","431615,03",0
7,2015S006560,10.0,Sant Martí,64.0,el Camp de l'Arpa del Clot,161407.0,Indústria,Monday,1,Labor,...,Afternoon,It is not the cause of the pedestrian,0.0,2.0,0.0,2.0,2.0,"4585306,47","431650,48",0

In [250]:
df5.isnull().sum()

case_id                 0
district_id             0
district_name           0
neighborhood_id         0
neighborhood_name       0
street_code             0
street_name             1
weekday_name            0
weekday                 0
type_day             7659
year                    0
month                   0
month_name              0
day                     0
hour                    0
cyrcadian               0
cause_incident          0
n_deaths                0
n_wounded_mild          0
n_wounded_severe        0
n_victims               0
n_vehicles              0
utm_coordinate_y        0
utm_coordinate_x        0
working                 0
dtype: int64

In [251]:
df5 = df5.drop('type_day', axis='columns')

In [254]:
df5[df5['street_name'].isnull()]

,case_id,district_id,district_name,neighborhood_id,neighborhood_name,street_code,street_name,weekday_name,weekday,year,...,cyrcadian,cause_incident,n_deaths,n_wounded_mild,n_wounded_severe,n_victims,n_vehicles,utm_coordinate_y,utm_coordinate_x,working
98326,2018S008677,5.0,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",71406.0,NaN,Monday,1,2018.0,...,Nit,It is not the cause of the pedestrian,0.0,0.0,0.0,0.0,0.0,4585165.96,425082.72,0

In [257]:
df5 = df5.drop(98326, axis = 0)

In [258]:
df5.isnull().any()

case_id              False
district_id          False
district_name        False
neighborhood_id      False
neighborhood_name    False
street_code          False
street_name          False
weekday_name         False
weekday              False
year                 False
month                False
month_name           False
day                  False
hour                 False
cyrcadian            False
cause_incident       False
n_deaths             False
n_wounded_mild       False
n_wounded_severe     False
n_victims            False
n_vehicles           False
utm_coordinate_y     False
utm_coordinate_x     False
working              False
dtype: bool

In [ ]:
#DATA CLEANING COMPLETE